# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='color',
            field=models.CharField(choices=[('capl', 'CAPL'), ('capl-xml', 'CAPL-XML')], default='capl', max_length=6),
        ),
        migrations.AddField(
            model_name='upload',
            name='sheet',
            field=models.CharField(default='Sheet', max_length=40),
        ),
    ]
