# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzip', '0002_auto_20180723_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='color',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sheet',
        ),
        migrations.AddField(
            model_name='upload',
            name='option',
            field=models.CharField(choices=[('capl', 'CAPL'), ('capl-xml', 'CAPL-XML')], default='capl-xml', max_length=8),
        ),
        migrations.AddField(
            model_name='upload',
            name='sheet_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
